package ECHOAPP;


/**
* ECHOAPP/EchoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from echo.idl
* miércoles 30 de marzo de 2016 20H49' CEST
*/

abstract public class EchoHelper
{
  private static String  _id = "IDL:ECHOAPP/Echo:1.0";

  public static void insert (org.omg.CORBA.Any a, ECHOAPP.Echo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ECHOAPP.Echo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ECHOAPP.EchoHelper.id (), "Echo");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ECHOAPP.Echo read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EchoStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ECHOAPP.Echo value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ECHOAPP.Echo narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ECHOAPP.Echo)
      return (ECHOAPP.Echo)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ECHOAPP._EchoStub stub = new ECHOAPP._EchoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ECHOAPP.Echo unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ECHOAPP.Echo)
      return (ECHOAPP.Echo)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ECHOAPP._EchoStub stub = new ECHOAPP._EchoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
