package ECHOAPP;


/**
* ECHOAPP/Echo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from echo.idl
* miércoles 30 de marzo de 2016 20H49' CEST
*/

public interface Echo extends EchoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Echo
