package ECHOAPP;

/**
* ECHOAPP/EchoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from echo.idl
* miércoles 30 de marzo de 2016 20H49' CEST
*/

public final class EchoHolder implements org.omg.CORBA.portable.Streamable
{
  public ECHOAPP.Echo value = null;

  public EchoHolder ()
  {
  }

  public EchoHolder (ECHOAPP.Echo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ECHOAPP.EchoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ECHOAPP.EchoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ECHOAPP.EchoHelper.type ();
  }

}
