package ECHOAPP;


/**
* ECHOAPP/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from echo.idl
* miércoles 30 de marzo de 2016 20H49' CEST
*/

public interface EchoOperations 
{
  String echoString (String mesg);
} // interface EchoOperations
