package chat;


/**
* chat/peertopeerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 15 de abril de 2016 11H54' CEST
*/

public interface peertopeerOperations 
{
  void sendMessge (chat.VOUser usuario, String message);
  void sendFile (chat.VOUser usuario, byte[] archivo, String nombre);
} // interface peertopeerOperations
