package chat;

/**
* chat/peertopeerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* jueves 14 de abril de 2016 00H45' CEST
*/

public final class peertopeerHolder implements org.omg.CORBA.portable.Streamable
{
  public chat.peertopeer value = null;

  public peertopeerHolder ()
  {
  }

  public peertopeerHolder (chat.peertopeer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chat.peertopeerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chat.peertopeerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chat.peertopeerHelper.type ();
  }

}
