package chat;

/**
* chat/supertopeerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* lunes 11 de abril de 2016 12H11' CEST
*/


/*
  Interfaz para enviat notificacións desede o servidor aos clientes.
  considerar convertir as notificacións a oneway para que  non espere o servidor
  a comprobar si os clientes recibiron ou no a notificación correspondiente
*/
public final class supertopeerHolder implements org.omg.CORBA.portable.Streamable
{
  public chat.supertopeer value = null;

  public supertopeerHolder ()
  {
  }

  public supertopeerHolder (chat.supertopeer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chat.supertopeerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chat.supertopeerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chat.supertopeerHelper.type ();
  }

}
