package chat;


/**
* chat/userManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 15 de abril de 2016 11H54' CEST
*/

public interface userManagerOperations 
{
  boolean signIn (chat.VOUserHolder usuario);
  boolean signOut (chat.VOUser usuario);
  boolean signUp (chat.VOUser usuario);
  boolean alterUser (chat.VOUser usuario);
  boolean deleteUser (chat.VOUser usuario);
  chat.VOUser[] getFrindList (chat.VOUser usuario);
  chat.VOUser[] getUserLike (chat.VOUser usuario, chat.VOUser busqueda);
  boolean newFriendRequest (chat.VOUser origin, chat.VOUser destiny);
  boolean resolveFriendRequest (chat.VOUser origin, chat.VOUser destiny, boolean accept);
} // interface userManagerOperations
