module chat
{
  /*
    Interfaz para enviat notificacións desede o servidor aos clientes.
    considerar convertir as notificacións a oneway para que  non espere o servidor
    a comprobar si os clientes recibiron ou no a notificación correspondiente
  */

  interface supertopeer;
  interface peertopeer;

  typedef sequence<octet> file;

  struct VOUser{
    short id;
    string nombre;
    string email;
    string hash;
    string salt;
    string avatar;
    supertopeer callback;
    peertopeer chat;
  };

  interface peertopeer{
    void sendMessge(in VOUser usuario,in string message);
    void sendFile(in VOUser usuario,in file archivo, in string nombre);
  };

  interface supertopeer {
    void notifyFriendIn(in VOUser usuario);
    void notifyFriendOut(in VOUser usuario);
    void notifyFriendRequest(in VOUser usuario);
    void notifyFriendRequestReslution(in VOUser usuario,in boolean result);
  };

  typedef sequence<VOUser> listaUsuarios;

  interface userManager{
    boolean signIn(inout VOUser usuario);
    boolean signOut(in VOUser usuario);
    boolean signUp(in VOUser usuario);
    boolean alterUser(in VOUser usuario);
    boolean deleteUser(in VOUser usuario);
    listaUsuarios getFrindList(in VOUser usuario);
    listaUsuarios getUserLike(in VOUser usuario,in VOUser busqueda);
    boolean newFriendRequest(in VOUser origin,in VOUser destiny);
    boolean resolveFriendRequest(in VOUser origin,in VOUser destiny,in boolean accept);
  };

};
