package chat;


/**
* chat/supertopeer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* miércoles 13 de abril de 2016 15H56' CEST
*/

public interface supertopeer extends supertopeerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface supertopeer
