package chat;

/**
* chat/supertopeerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* miércoles 13 de abril de 2016 15H56' CEST
*/

public final class supertopeerHolder implements org.omg.CORBA.portable.Streamable
{
  public chat.supertopeer value = null;

  public supertopeerHolder ()
  {
  }

  public supertopeerHolder (chat.supertopeer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chat.supertopeerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chat.supertopeerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chat.supertopeerHelper.type ();
  }

}
