package chat;


/**
* chat/supertopeer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* mi�rcoles 13 de abril de 2016 14H50' CEST
*/


/*
    Interfaz para enviat notificacións desede o servidor aos clientes.
    considerar convertir as notificacións a oneway para que  non espere o servidor
    a comprobar si os clientes recibiron ou no a notificación correspondiente
  */
public interface supertopeer extends supertopeerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface supertopeer
