package chat;


/**
* chat/supertopeerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* jueves 14 de abril de 2016 18H51' CEST
*/

public interface supertopeerOperations 
{
  void notifyFriendIn (chat.VOUser usuario);
  void notifyFriendOut (chat.VOUser usuario);
  void notifyFriendRequest (chat.VOUser usuario);
  void notifyFriendRequestReslution (chat.VOUser usuario, boolean result);
} // interface supertopeerOperations
