package chat;


/**
* chat/userManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* miércoles 13 de abril de 2016 14H50' CEST
*/

public interface userManagerOperations 
{
  boolean signIn (chat.VOUserHolder usuario, chat.supertopeer callback);
  boolean signOut (chat.VOUser usuario);
  boolean signUp (chat.VOUser usuario);
  boolean alterUser (chat.VOUser usuario);
  chat.VOUser[] getFrindList (chat.VOUser usuario);
  boolean newFriendRequest (chat.VOUser origin, chat.VOUser destiny);
  boolean resolveFriendRequest (chat.VOUser origin, chat.VOUser destiny, boolean accept);
} // interface userManagerOperations
