package chat;


/**
* chat/userManagerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* miércoles 13 de abril de 2016 15H56' CEST
*/

public abstract class userManagerPOA extends org.omg.PortableServer.Servant
 implements chat.userManagerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("signIn", new java.lang.Integer (0));
    _methods.put ("signOut", new java.lang.Integer (1));
    _methods.put ("signUp", new java.lang.Integer (2));
    _methods.put ("alterUser", new java.lang.Integer (3));
    _methods.put ("getFrindList", new java.lang.Integer (4));
    _methods.put ("newFriendRequest", new java.lang.Integer (5));
    _methods.put ("resolveFriendRequest", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // chat/userManager/signIn
       {
         chat.VOUserHolder usuario = new chat.VOUserHolder ();
         usuario.value = chat.VOUserHelper.read (in);
         boolean $result = false;
         $result = this.signIn (usuario);
         out = $rh.createReply();
         out.write_boolean ($result);
         chat.VOUserHelper.write (out, usuario.value);
         break;
       }

       case 1:  // chat/userManager/signOut
       {
         chat.VOUser usuario = chat.VOUserHelper.read (in);
         boolean $result = false;
         $result = this.signOut (usuario);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // chat/userManager/signUp
       {
         chat.VOUser usuario = chat.VOUserHelper.read (in);
         boolean $result = false;
         $result = this.signUp (usuario);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // chat/userManager/alterUser
       {
         chat.VOUser usuario = chat.VOUserHelper.read (in);
         boolean $result = false;
         $result = this.alterUser (usuario);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // chat/userManager/getFrindList
       {
         chat.VOUser usuario = chat.VOUserHelper.read (in);
         chat.VOUser $result[] = null;
         $result = this.getFrindList (usuario);
         out = $rh.createReply();
         chat.listaUsuariosHelper.write (out, $result);
         break;
       }

       case 5:  // chat/userManager/newFriendRequest
       {
         chat.VOUser origin = chat.VOUserHelper.read (in);
         chat.VOUser destiny = chat.VOUserHelper.read (in);
         boolean $result = false;
         $result = this.newFriendRequest (origin, destiny);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // chat/userManager/resolveFriendRequest
       {
         chat.VOUser origin = chat.VOUserHelper.read (in);
         chat.VOUser destiny = chat.VOUserHelper.read (in);
         boolean accept = in.read_boolean ();
         boolean $result = false;
         $result = this.resolveFriendRequest (origin, destiny, accept);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:chat/userManager:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public userManager _this() 
  {
    return userManagerHelper.narrow(
    super._this_object());
  }

  public userManager _this(org.omg.CORBA.ORB orb) 
  {
    return userManagerHelper.narrow(
    super._this_object(orb));
  }


} // class userManagerPOA
