package chat;


/**
* chat/userManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 12 de abril de 2016 16H59' CEST
*/

public interface userManagerOperations 
{
  boolean signIn (chat.VOUserHolder usuario);
  boolean signOut (chat.VOUser usuario);
  boolean signUp (chat.VOUser usuario);
  boolean alterUser (chat.VOUser usuario);
  boolean getFrindList (chat.VOUser usuario, chat.listaUsuariosHolder usuarios);
  boolean newFriendRequest (chat.VOUser origin, chat.VOUser destiny);
  boolean resolveFriendRequest (chat.VOUser origin, chat.VOUser destiny, boolean accept);
} // interface userManagerOperations
