package chat;


/**
* chat/userManager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 10 de abril de 2016 00H18' CEST
*/

public interface userManager extends userManagerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface userManager
