package chat;


/**
* chat/userManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 10 de abril de 2016 00H18' CEST
*/

public interface userManagerOperations 
{
  boolean signIn (chat.VOUser usuario);
  boolean signOut (chat.VOUser usuario);
  boolean signUp (chat.VOUser usuario);
  boolean alterUser (chat.VOUser usuario);
  chat.VOUser[] getFrindList (chat.VOUser usuario);
} // interface userManagerOperations
