package chat;


/**
* chat/userManagerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 12 de abril de 2016 16H59' CEST
*/

abstract public class userManagerHelper
{
  private static String  _id = "IDL:chat/userManager:1.0";

  public static void insert (org.omg.CORBA.Any a, chat.userManager that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static chat.userManager extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (chat.userManagerHelper.id (), "userManager");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static chat.userManager read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_userManagerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, chat.userManager value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static chat.userManager narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof chat.userManager)
      return (chat.userManager)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      chat._userManagerStub stub = new chat._userManagerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static chat.userManager unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof chat.userManager)
      return (chat.userManager)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      chat._userManagerStub stub = new chat._userManagerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
