package chat;


/**
* chat/VOUser.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 12 de abril de 2016 20H41' CEST
*/

public final class VOUser implements org.omg.CORBA.portable.IDLEntity
{
  public short id = (short)0;
  public String nombre = null;
  public String email = null;
  public String hash = null;
  public String salt = null;
  public String avatar = null;

  public VOUser ()
  {
  } // ctor

  public VOUser (short _id, String _nombre, String _email, String _hash, String _salt, String _avatar)
  {
    id = _id;
    nombre = _nombre;
    email = _email;
    hash = _hash;
    salt = _salt;
    avatar = _avatar;
  } // ctor

} // class VOUser
