package chat;


/**
* chat/VOUser.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 15 de abril de 2016 11H54' CEST
*/

public final class VOUser implements org.omg.CORBA.portable.IDLEntity
{
  public short id = (short)0;
  public String nombre = null;
  public String email = null;
  public String hash = null;
  public String salt = null;
  public String avatar = null;
  public chat.supertopeer callback = null;
  public chat.peertopeer chat = null;

  public VOUser ()
  {
  } // ctor

  public VOUser (short _id, String _nombre, String _email, String _hash, String _salt, String _avatar, chat.supertopeer _callback, chat.peertopeer _chat)
  {
    id = _id;
    nombre = _nombre;
    email = _email;
    hash = _hash;
    salt = _salt;
    avatar = _avatar;
    callback = _callback;
    chat = _chat;
  } // ctor

} // class VOUser
